import Head from "next/head";
import Image from "next/image";
import LogoBig from "/public/images/Icons/logo-golemo.svg";
import CircleSmall from "/public/images/background-images/krug-pogolem.svg";
import CircleBig from "/public/images/background-images/krug-pomal.svg";
import Link from "next/link";
import CardModal from "@/components/heder-components/CardModal";
import CheckIcon from "/public/images/Icons/inputcheck.svg";
import LocationIcon from "/public/images/Icons/inputlocation.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Јади домашно</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="xl:flex xl:justify-center items-center xl:pt-40 xl:pb-40 pb-10 pt-10 relative">
        <Image
          priority
          src="/images/background-images/foood2.png"
          alt="bg-image"
          className="absolute right-0 top-1 z-0 hidden lg:block"
          width={590}
          height={637}
        />
        <CircleSmall
          className="absolute right-0 top-[200px] z-0 hidden lg:block"
          priority
        />
        <CircleBig
          className="absolute right-0 top-[450px] z-0 hidden lg:block"
          priority
          width={90}
          height={333}
        />

        <div>
          <div className="flex justify-center items-center">
            <LogoBig width={105} height={112} />
            <h1 className="xl:text-6xl text-OrangeSecondary xl:font-outline ">
              Јади домашно
            </h1>
          </div>
          <div className="flex items-center justify-center pt-5">
            <hr className=" xl:w-32 w-16 border-2 border-OrangeSecondary" />
            <h2 className=" font-badscript xl:text-[40px] pl-2 pr-2">
              Вкусот на твоето соседство!
            </h2>
            <hr className=" xl:w-32 w-16 border-2 border-OrangeSecondary" />
          </div>
          <div className="pt-10 pb-10">
            <form className="xl:flex items-center mx-auto justify-between">
              <div className="relative xl:flex items-center  ">
                <input
                  type="text"
                  placeholder="Внеси адреса"
                  className="py-2 text-sm bg-GreyPrimary shadow-lg text-black rounded-[20px] placeholder:text-black  focus:outline-none focus:bg-white focus:text-gray-900 xl:w-80 w-full xl:h-12 h-10 placeholder:text-xs xl:placeholder:text-lg pl-14"
                />
                <CheckIcon className=" absolute  right-4 xl:bottom-[9px] bottom-[7px] mr-2" />
                <LocationIcon className=" absolute left-4 xl:bottom-[9px] bottom-[3px]" />
              </div>

              <div className="pt-5 xl:pt-0 flex justify-center">
                <button
                  type="submit"
                  className=" py-2 bg-OrangePrimary shadow-lg text-white rounded-[20px]  xl:w-72 w-40 xl:h-10 font-medium text-sm xl:block text-center cursor-pointer"
                >
                  Погледни резултати
                </button>
              </div>
            </form>
          </div>
        </div>
        <div className="z-10">
          <Image
            priority
            src="/images/images-static/tavce gravce.png"
            width={713}
            height={675}
            alt="Tavce Gravce"
            className=" z-10"
          />
        </div>
        <Image
          src="/images/background-images/food3.png"
          className=" absolute top-[650px] left-0 hidden lg:block"
          alt="Food"
          width={390}
          height={437}
        />
      </section>
      <section className="xl:pt-20 xl:pb-20 pb-10 relative">
        <div className="flex items-center justify-center">
          <hr className=" xl:w-32 w-16 border-2 border-OrangeSecondary" />
          <h2 className=" font-badscript xl:text-[40px] pl-4 pr-4">
            Нашите вредности
          </h2>
          <hr className=" xl:w-32 w-16 border-2 border-OrangeSecondary" />
        </div>
        <div className=" xl:grid xl:grid-cols-3 flex-col items-center justify-around text-center pt-20">
          <div>
            <Image
              priority
              src="/images/images-static/img1.png"
              alt="Поврзување!"
              width={278}
              height={278}
              className="mx-auto"
            />
            <h2 className=" font-badscript xl:text-[40px] text-black pb-5">
              Поврзување!
            </h2>
            <p className="xl:text-xl text-black">
              Вистински луѓе. Автентична љубов.
            </p>
          </div>
          <div>
            <div>
              <Image
                priority
                src="/images/images-static/img2.png"
                alt="Поврзување!"
                width={278}
                height={278}
                className="mx-auto"
              />
              <h2 className=" font-badscript xl:text-[40px] text-black pb-5">
                Споделување на радост!
              </h2>
              <p className="xl:text-xl text-black">
                Уживајте во заедницата преку храна.
              </p>
            </div>
          </div>
          <div>
            <div>
              <Image
                priority
                src="/images/images-static/img3.png"
                alt="Поврзување!"
                width={278}
                height={278}
                className="mx-auto"
              />
              <h2 className=" font-badscript xl:text-[40px] text-black pb-5">
                Кулинарски можности!
              </h2>
              <p className="xl:text-xl text-black">
                Зајакнување на домашните готвачи.
              </p>
            </div>
          </div>
        </div>
        <div className="flex justify-center items-center xl:pt-10">
          <Link
            href="/"
            className=" py-2 bg-OrangePrimary text-white rounded-[20px] xl:w-96 w-48 xl:h-10 font-medium text-sm mt-5 xl:block text-center"
          >
            Дознај повеќе за нас
          </Link>
        </div>
      </section>
    </>
  );
}
